import {useMutation, useQuery, useQueryClient} from '@tanstack/react-query';
import {Bot, FileImage, FileSearch, FileVideo2, Filter, Fingerprint, Search, Send, ServerCog, ShieldAlert, Trash2} from 'lucide-react';
import {useMemo, useState} from 'react';
import {Link, useNavigate} from 'react-router-dom';
import {api} from '../lib/api';
import {dateTime, label, percent} from '../lib/format';
import {PrivateImage} from '../components/PrivateImage';
import {EmptyState, Glass, Loading, PageHeader, SignalBadge} from '../components/UI';
import type {Analysis, Explanation} from '../types';

function useAnalyses(){return useQuery({queryKey:['analyses'],queryFn:()=>api<Analysis[]>('/analyses')})}

export function HistoryPage(){const {data,isLoading}=useAnalyses();const client=useQueryClient();const [search,setSearch]=useState('');const [filter,setFilter]=useState('ALL');const navigate=useNavigate();const remove=useMutation({mutationFn:(id:string)=>api(`/analyses/${id}`,{method:'DELETE'}),onSuccess:()=>client.invalidateQueries({queryKey:['analyses']})});const items=useMemo(()=>data?.filter(item=>(!search||item.original_filename.toLowerCase().includes(search.toLowerCase()))&&(filter==='ALL'||item.classification===filter||item.media_type===filter||(filter==='REVIEWED'&&item.review)))||[],[data,search,filter]);
  if(isLoading)return <Loading/>;return <div className="page library-page"><PageHeader kicker="ANALYSIS HISTORY / REAL RECORDS" title="Forensic history" description="Search, reopen, or delete your persisted analysis records."/><Glass className="library-controls"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search original filename"/></label><div><Filter/>{['ALL','LIKELY_AUTHENTIC','LIKELY_MANIPULATED','INCONCLUSIVE','IMAGE','VIDEO','REVIEWED'].map(item=><button className={filter===item?'active':''} onClick={()=>setFilter(item)} key={item}>{label(item)}</button>)}</div></Glass>{!items.length?<EmptyState title={data?.length?'No analyses match':'No analyses yet'} copy={data?.length?'Adjust the filters to inspect another part of your history.':'Submit suspicious media to begin.'} action={<Link to="/app/analyse" className="primary-button">START ANALYSIS</Link>}/>:<Glass className="history-list"><div className="table-head"><span>FILE</span><span>MODEL RESULT</span><span>PROBABILITY</span><span>QUALITY</span><span>HUMAN REVIEW</span><span>DATE</span><span/></div>{items.map(item=><div className="table-row" key={item.id} onClick={()=>navigate(`/app/analyses/${item.id}`)} role="link" tabIndex={0}><span className="media-cell">{item.media_type==='IMAGE'?<FileImage/>:<FileVideo2/>}<b>{item.original_filename}<small>{item.media_type} · {item.status}</small></b></span><SignalBadge value={item.classification||item.status}/><strong>{percent(item.fake_probability)}</strong><span>{label(item.quality_status)}</span><span>{label(item.review?.decision||'UNREVIEWED')}</span><small>{dateTime(item.created_at)}</small><button aria-label={`Delete ${item.original_filename}`} onClick={event=>{event.stopPropagation();if(confirm(`Delete ${item.original_filename} and all derived evidence?`))remove.mutate(item.id)}}><Trash2/></button></div>)}</Glass>}</div>}

export function EvidencePage(){const {data,isLoading}=useAnalyses();if(isLoading)return <Loading/>;const items=data?.filter(item=>item.status==='COMPLETED'&&item.has_preview)||[];return <div className="page library-page"><PageHeader kicker="EVIDENCE LIBRARY / PRIVATE DERIVED ASSETS" title="Evidence explorer" description="Browse completed analyses containing private visual evidence."/>{!items.length?<EmptyState title="No evidence maps" copy="Completed analyses with usable derived previews will appear here."/>:<div className="evidence-grid">{items.map(item=><Link to={`/app/analyses/${item.id}`} key={item.id}><Glass><PrivateImage path={`/analyses/${item.id}/assets/${item.media_type==='IMAGE'?'overlay':'preview'}`} alt={`Evidence for ${item.original_filename}`}/><div><SignalBadge value={item.classification}/><h3>{item.original_filename}</h3><p>{item.media_type} · {label(item.quality_status)} · {dateTime(item.created_at)}</p><strong>{percent(item.fake_probability)}</strong></div></Glass></Link>)}</div>}</div>}

type Audit={id:string;analysis_id?:string;action:string;previous_value?:object;new_value?:object;note?:string;model_id?:string;created_at:string};
export function AuditPage(){const {data,isLoading}=useQuery({queryKey:['audit'],queryFn:()=>api<Audit[]>('/audit')});if(isLoading)return <Loading/>;return <div className="page audit-page"><PageHeader kicker="AUDIT TRAIL / IMMUTABLE EVENT HISTORY" title="Review trace" description="Model activity and human decisions remain visible as separate events."/>{!data?.length?<EmptyState title="No audit events" copy="Analysis, explanation, review, note, and deletion events will appear here."/>:<Glass className="audit-timeline">{data.map(item=><article key={item.id}><span><Fingerprint/></span><div><small>{dateTime(item.created_at)}</small><h3>{label(item.action)}</h3>{item.analysis_id&&<Link to={`/app/analyses/${item.analysis_id}`}>ANALYSIS {item.analysis_id.slice(0,8).toUpperCase()}</Link>}{item.note&&<p>{item.note}</p>}<em>{item.model_id||'HUMAN / SYSTEM EVENT'}</em></div></article>)}</Glass>}</div>}

export function AnalystPage(){const {data:analyses,isLoading}=useAnalyses();const [analysisId,setAnalysisId]=useState('');const [question,setQuestion]=useState('Explain this result simply');const [answers,setAnswers]=useState<{question:string;answer:Explanation}[]>([]);const ask=useMutation({mutationFn:()=>api<Explanation>('/ai/ask',{method:'POST',body:JSON.stringify({analysis_id:analysisId,question})}),onSuccess:answer=>{setAnswers(items=>[...items,{question,answer}]);setQuestion('')}});const completed=analyses?.filter(item=>item.status==='COMPLETED')||[];if(isLoading)return <Loading/>;return <div className="page analyst-page"><PageHeader kicker="FORENSIC INTELLIGENCE COPILOT / GROUNDED CONTEXT" title="Ask against evidence" description="The copilot can only use the selected analysis, detector signal, quality context, and review notes."/>{!completed.length?<EmptyState title="No completed context" copy="Complete an analysis before asking the evidence-grounded copilot."/>:<div className="analyst-layout"><Glass className="context-selector"><div className="module-head"><span>CONTEXT/ANALYSIS</span><FileSearch/></div><select value={analysisId} onChange={e=>setAnalysisId(e.target.value)}><option value="">Select completed analysis</option>{completed.map(item=><option value={item.id} key={item.id}>{item.original_filename} — {label(item.classification)}</option>)}</select>{analysisId&&<><PrivateImage path={`/analyses/${analysisId}/assets/preview`} alt="Selected analysis context"/><p><ShieldAlert/>Raw media is not sent to the language model. Only structured evidence is used.</p></>}</Glass><Glass className="copilot-thread"><div className="module-head"><span>FORENSIC/COPILOT</span><Bot/></div>{!answers.length?<div className="copilot-empty"><Bot/><h2>Ask a review question</h2><p>Try: “What quality limitations are present?” or “What should a human reviewer inspect next?”</p></div>:answers.map((item,index)=><article key={index}><div className="question">{item.question}</div><div className="structured-answer"><h3>SUMMARY</h3><p>{item.answer.summary}</p><h3>MODEL EVIDENCE</h3><p>{item.answer.evidence_interpretation}</p><h3>QUALITY CONTEXT</h3><p>{item.answer.quality_context}</p><h3>RECOMMENDED HUMAN CHECK</h3><p>{item.answer.recommended_review}</p><h3>LIMITATIONS</h3><p>{item.answer.limitations}</p></div></article>)}<form onSubmit={e=>{e.preventDefault();if(analysisId&&question.trim())ask.mutate()}}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about the selected analysis…"/><button disabled={!analysisId||!question.trim()||ask.isPending}><Send/></button></form></Glass></div>}</div>}

type ModelInfo={model_id:string;architecture:string;device:string;labels:string[];loaded:boolean;calibrated:boolean;evidence_method:string;error?:string;thresholds:{authentic:number;manipulated:number}};
export function SettingsPage(){const {data,isLoading,refetch,isFetching}=useQuery({queryKey:['model'],queryFn:()=>api<ModelInfo>('/system/model')});if(isLoading)return <Loading/>;return <div className="page settings-page"><PageHeader kicker="SYSTEM / MODEL INFORMATION" title="Detector configuration" description="Public runtime metadata only. Private checkpoint paths and secrets are never exposed."/><div className="settings-grid"><Glass><div className="module-head"><span>DETECTOR/METADATA</span><ServerCog/></div>{data&&[['ARCHITECTURE',data.architecture],['MODEL IDENTIFIER',data.model_id],['DEVICE',data.device.toUpperCase()],['LABELS',data.labels.join(' · ')||'Loads on first analysis'],['EVIDENCE METHOD',label(data.evidence_method)],['CALIBRATION',data.calibrated?'AVAILABLE':'NOT CONFIGURED']].map(([key,value])=><span className="settings-row" key={key}><small>{key}</small><b>{value}</b></span>)}<button className="ghost-button" onClick={()=>refetch()} disabled={isFetching}>REFRESH STATUS</button></Glass><Glass className="model-state"><span className={data?.loaded?'online':'standby'}><i/></span><h2>{data?.loaded?'MODEL LOADED':'MODEL LOADS ON FIRST ANALYSIS'}</h2><p>{data?.error||'The singleton model manager prevents reloading the detector for every request.'}</p><div><b>AUTHENTIC BAND</b><span>≤ {percent(data?.thresholds.authentic)}</span><b>INCONCLUSIVE BAND</b><span>{percent(data?.thresholds.authentic)} – {percent(data?.thresholds.manipulated)}</span><b>MANIPULATED BAND</b><span>≥ {percent(data?.thresholds.manipulated)}</span></div></Glass><Glass className="responsible-card"><ShieldAlert/><h2>Screening support, not forensic certainty</h2><p>Deepfake detectors can fail on unseen generation methods. Compression and poor quality can reduce reliability. Attention maps indicate model influence rather than definitive manipulation masks. Never use one score as the sole basis for a consequential decision.</p></Glass></div></div>}
