import {useDropzone} from 'react-dropzone';
import {AnimatePresence, motion} from 'framer-motion';
import {ArrowRight, CheckCircle2, FileImage, FileVideo2, RefreshCw, ScanLine, ShieldAlert, UploadCloud, X} from 'lucide-react';
import {useMemo, useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api} from '../lib/api';
import {bytes} from '../lib/format';
import {Glass, Kicker, PageHeader} from '../components/UI';

export function NewAnalysis() {
  const navigate=useNavigate(); const [mediaType,setMediaType]=useState<'IMAGE'|'VIDEO'>('IMAGE'); const [file,setFile]=useState<File|null>(null); const [mode,setMode]=useState<'standard'|'detailed'>('standard'); const [retain,setRetain]=useState(false); const [error,setError]=useState(''); const [uploading,setUploading]=useState(false);
  const preview=useMemo(()=>file?URL.createObjectURL(file):'', [file]);
  const dropzone=useDropzone({multiple:false,maxSize:(mediaType==='IMAGE'?15:80)*1024*1024,accept:mediaType==='IMAGE'?{'image/jpeg':['.jpg','.jpeg'],'image/png':['.png'],'image/webp':['.webp']}:{'video/mp4':['.mp4'],'video/quicktime':['.mov'],'video/webm':['.webm'],'video/x-msvideo':['.avi']},onDropAccepted:files=>{setFile(files[0]);setError('');},onDropRejected:rejections=>setError(rejections[0]?.errors[0]?.message||'Unsupported media')});
  const submit=async()=>{if(!file)return;setUploading(true);setError('');const body=new FormData();body.append('file',file);body.append('mode',mode);body.append('retain_original',String(retain));try{const result=await api<{id:string;duplicate_analysis_id?:string}>(`/analyses/${mediaType.toLowerCase()}`,{method:'POST',body});navigate(`/app/analyses/${result.id}/processing`,{state:{duplicate:result.duplicate_analysis_id}});}catch(e){setError(e instanceof Error?e.message:'Upload failed');setUploading(false);}};
  return <div className="page analyse-page"><PageHeader kicker="NEW ANALYSIS / PRIVATE MEDIA INTAKE" title="Acquire media evidence" description="Nothing runs until you confirm the file and analysis configuration."/>
    <div className="stepper">{['MEDIA','VALIDATE','CONFIGURE','ANALYSE','REVIEW'].map((stage,index)=><span key={stage} className={index===0?'active':''}><i>{String(index+1).padStart(2,'0')}</i>{stage}<em/></span>)}</div>
    <div className="analysis-builder"><Glass className="intake-panel"><div className="media-switch"><button className={mediaType==='IMAGE'?'active':''} onClick={()=>{setMediaType('IMAGE');setFile(null)}}><FileImage/>IMAGE<small>JPG · PNG · WEBP</small></button><button className={mediaType==='VIDEO'?'active':''} onClick={()=>{setMediaType('VIDEO');setFile(null)}}><FileVideo2/>VIDEO<small>MP4 · MOV · WEBM</small></button></div>
      <AnimatePresence mode="wait">{!file?<motion.div key="drop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div {...dropzone.getRootProps()} className={`drop-zone ${dropzone.isDragActive?'dragging':''}`}><input {...dropzone.getInputProps()}/><div className="acquire-visual"><UploadCloud/><span/><i/></div><Kicker>SECURE MEDIA ACQUISITION</Kicker><h2>{dropzone.isDragActive?'Release to acquire':'Drop suspicious media here'}</h2><p>or click to choose a {mediaType.toLowerCase()} · maximum {mediaType==='IMAGE'?'15 MB':'80 MB / 60 seconds'}</p><button className="ghost-button" type="button">CHOOSE {mediaType}</button></div></motion.div>:<motion.div key="preview" className="selected-media" initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}}><div className="media-preview">{mediaType==='IMAGE'?<img src={preview} alt="Selected media preview"/>:<video src={preview} controls/>}<div className="preview-scan"/></div><div className="file-data"><Kicker>MEDIA ACQUIRED / AWAITING CONFIRMATION</Kicker><h2>{file.name}</h2><div><span><b>TYPE</b>{file.type}</span><span><b>SIZE</b>{bytes(file.size)}</span><span><b>MODIFIED</b>{new Date(file.lastModified).toLocaleDateString()}</span></div><button onClick={()=>setFile(null)}><X/>REMOVE</button></div></motion.div>}</AnimatePresence>{error&&<div className="upload-error"><ShieldAlert/>{error}</div>}</Glass>
      <Glass className="configuration"><div className="module-head"><span>ANALYSIS/CONFIG</span><b>FUNCTIONAL OPTIONS</b></div><h2>Configure screening</h2><label>Analysis mode<div className="mode-grid"><button className={mode==='standard'?'active':''} onClick={()=>setMode('standard')}><CheckCircle2/><b>STANDARD</b><small>Balanced frame sampling</small></button><button className={mode==='detailed'?'active':''} onClick={()=>setMode('detailed')}><ScanLine/><b>DETAILED</b><small>Denser frame sampling</small></button></div></label><label>Evidence method<div className="locked-option"><b>ATTENTION ROLLOUT</b><small>ViT token influence visualization</small></div></label><label className="toggle-row"><span><b>Retain original media</b><small>Off by default. Derived previews remain private.</small></span><input type="checkbox" checked={retain} onChange={e=>setRetain(e.target.checked)}/></label><div className="privacy-note"><ShieldAlert/><span><b>PRIVATE PROCESSING</b>Raw media is never sent to OpenRouter. Local raw media is deleted after analysis unless backend retention is enabled.</span></div><button className="primary-button analyse-submit" onClick={submit} disabled={!file||uploading}>{uploading?<><RefreshCw className="spin"/>ACQUIRING MEDIA</>:<>START ANALYSIS <ArrowRight/></>}</button></Glass>
    </div></div>;
}
