import {useMutation, useQuery, useQueryClient} from '@tanstack/react-query';
import {Area, AreaChart, CartesianGrid, ReferenceArea, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import {Bot, CheckCircle2, ChevronLeft, Eye, FileImage, FileVideo2, MessageSquarePlus, ShieldAlert, TriangleAlert, ZoomIn} from 'lucide-react';
import {useEffect, useState} from 'react';
import {Link, useParams} from 'react-router-dom';
import {api} from '../lib/api';
import {dateTime, label, percent} from '../lib/format';
import {PrivateImage} from '../components/PrivateImage';
import {Glass, Loading, PageHeader, SignalBadge} from '../components/UI';
import type {Analysis, Explanation, Frame} from '../types';

const tabs=['original','analysed','attention','overlay'] as const;
export function ResultWorkspace(){const {id}=useParams();const queryClient=useQueryClient();const [tab,setTab]=useState<typeof tabs[number]>('overlay');const [frame,setFrame]=useState<Frame>();const [note,setNote]=useState('');const [mobileTab,setMobileTab]=useState('RESULT');
  const {data,isLoading}=useQuery({queryKey:['analysis',id],queryFn:()=>api<Analysis>(`/analyses/${id}`)});const {data:frames=[]}=useQuery({queryKey:['frames',id],queryFn:()=>api<Frame[]>(`/analyses/${id}/frames`),enabled:data?.media_type==='VIDEO'});
  useEffect(()=>{if(frames.length&&!frame)setFrame(frames[0])},[frames,frame]);
  const review=useMutation({mutationFn:(decision:string)=>api(`/analyses/${id}/review`,{method:'POST',body:JSON.stringify({decision})}),onSuccess:()=>queryClient.invalidateQueries({queryKey:['analysis',id]})});
  const addNote=useMutation({mutationFn:()=>api(`/analyses/${id}/notes`,{method:'POST',body:JSON.stringify({note})}),onSuccess:()=>{setNote('');queryClient.invalidateQueries({queryKey:['analysis',id]})}});
  const explain=useMutation({mutationFn:()=>api<Explanation>('/ai/explain',{method:'POST',body:JSON.stringify({analysis_id:id})}),onSuccess:()=>queryClient.invalidateQueries({queryKey:['analysis',id]})});
  if(isLoading||!data)return <Loading label="ASSEMBLING EVIDENCE WORKSPACE"/>;if(data.status!=='COMPLETED')return <div className="page"><PageHeader kicker="ANALYSIS / UNAVAILABLE" title={data.status==='FAILED'?'No result was generated':'Analysis is still processing'} description={data.failure_reason||'The result workspace opens only after the model pipeline completes.'}/><Link className="ghost-button" to={`/app/analyses/${id}/processing`}>VIEW PIPELINE</Link></div>;
  const assetPath=frame?`/analyses/${id}/frames/${frame.id}/assets/${tab==='overlay'?'overlay':'preview'}`:`/analyses/${id}/assets/${tab}`;const fake=data.fake_probability||0;
  return <div className="page result-page"><PageHeader kicker={`ANALYSIS / ${data.id.slice(0,8).toUpperCase()}`} title="Evidence review workspace" description={`${data.original_filename} · ${dateTime(data.completed_at)}`} action={<Link to="/app/history" className="ghost-button"><ChevronLeft/>HISTORY</Link>}/><div className="mobile-result-tabs">{(data.media_type==='VIDEO'?['RESULT','FRAMES','EVIDENCE','REVIEW']:['RESULT','MEDIA','EVIDENCE','REVIEW']).map(item=><button onClick={()=>setMobileTab(item)} className={mobileTab===item?'active':''} key={item}>{item}</button>)}</div>
    <div className="result-workspace"><aside className={`result-left ${mobileTab==='FRAMES'||mobileTab==='RESULT'?'mobile-active':''}`}><Glass><div className="module-head"><span>ANALYSIS/OVERVIEW</span><b>{data.media_type}</b></div><div className="file-summary">{data.media_type==='IMAGE'?<FileImage/>:<FileVideo2/>}<span><b>{data.original_filename}</b><small>{data.width}×{data.height}{data.duration?` · ${data.duration.toFixed(1)}s`:''}</small></span></div><div className="metadata-list">{[['SHA-256',`${data.sha256.slice(0,14)}…`],['MODEL',data.model_id||'Unavailable'],['SCOPE',label(data.analysis_scope)],['FRAMES',String(data.analysed_frames)],['QUALITY',label(data.quality_status)]].map(([key,value])=><span key={key}><small>{key}</small><b>{value}</b></span>)}</div></Glass>
      {data.media_type==='VIDEO'&&<Glass className="frame-strip"><div className="module-head"><span>FRAME/TIMELINE</span><b>{frames.length} SAMPLED</b></div>{frames.map(item=><button key={item.id} className={item.id===frame?.id?'active':''} onClick={()=>setFrame(item)}><PrivateImage path={`/analyses/${id}/frames/${item.id}/assets/preview`} alt={`Frame at ${item.timestamp_ms} ms`}/><span><b>{(item.timestamp_ms/1000).toFixed(1)}s</b><i style={{width:percent(item.fake_probability)}}/></span></button>)}</Glass>}
      <Glass className="quality-card"><div className="module-head"><span>INPUT/QUALITY</span><b>{data.quality?.status}</b></div>{data.quality&&<>{[['RESOLUTION',`${data.width}×${data.height}`],['SHARPNESS',data.quality.blur_score.toFixed(1)],['BRIGHTNESS',data.quality.brightness.toFixed(1)],['CONTRAST',data.quality.contrast.toFixed(1)],['FACE DETECTED',data.quality.face_detected?'YES':'NO']].map(([key,value])=><span key={key}><small>{key}</small><b>{value}</b></span>)}{data.quality.warnings.map(warning=><p key={warning}><TriangleAlert/>{warning}</p>)}</>}</Glass></aside>
      <main className={`evidence-canvas ${mobileTab==='MEDIA'||mobileTab==='EVIDENCE'||mobileTab==='RESULT'?'mobile-active':''}`}><Glass><div className="evidence-tabs" role="tablist">{tabs.map(item=><button key={item} className={tab===item?'active':''} disabled={!!frame&&item!=='original'&&item!=='overlay'} onClick={()=>setTab(item)}>{item.toUpperCase()}</button>)}<span><ZoomIn/> PRIVATE ASSET</span></div><div className="evidence-media"><PrivateImage key={assetPath} path={assetPath} alt={`${label(tab)} evidence view`}/><div className="evidence-corners"><i/><i/><i/><i/></div></div><div className="evidence-legend"><span>LOW INFLUENCE</span><i/><span>HIGH INFLUENCE</span></div><p><Eye/>Highlighted regions contributed more strongly to the model prediction. Attention is not a pixel-level forged-region mask.</p></Glass>
      {data.media_type==='VIDEO'&&<Glass className="timeline-chart"><div className="module-head"><span>VIDEO/SCORE_TIMELINE</span><b>CLICK A POINT TO INSPECT</b></div><ResponsiveContainer width="100%" height={200}><AreaChart data={frames} onClick={(event: any)=>{const payload=event?.activePayload?.[0]?.payload as Frame|undefined;if(payload)setFrame(payload)}}><CartesianGrid stroke="#ffffff0a"/><ReferenceArea y1={0} y2={.35} fill="#34d399" fillOpacity={.08}/><ReferenceArea y1={.35} y2={.65} fill="#fbbf24" fillOpacity={.08}/><ReferenceArea y1={.65} y2={1} fill="#fb7185" fillOpacity={.08}/><XAxis dataKey="timestamp_ms" tickFormatter={v=>`${(v/1000).toFixed(0)}s`} stroke="#695a75"/><YAxis domain={[0,1]} tickFormatter={v=>`${v*100}%`} stroke="#695a75"/><Tooltip labelFormatter={v=>`${(Number(v)/1000).toFixed(2)}s`} formatter={v=>percent(Number(v))}/><Area type="monotone" dataKey="fake_probability" stroke="#e879f9" fill="#a855f733"/></AreaChart></ResponsiveContainer></Glass>}</main>
      <aside className={`result-review ${mobileTab==='REVIEW'||mobileTab==='RESULT'?'mobile-active':''}`}><Glass className="signal-panel"><div className="module-head"><span>MODEL/SIGNAL</span><b>{data.thresholds?.calibrated?'CALIBRATED':'UNCALIBRATED'}</b></div><SignalBadge value={data.classification}/><div className="probability-ring" style={{'--score':`${fake*360}deg`} as React.CSSProperties}><div><strong>{percent(fake)}</strong><small>MANIPULATED<br/>PROBABILITY</small></div></div><div className="spectrum"><span>AUTHENTIC</span><span>INCONCLUSIVE</span><span>MANIPULATED</span><i style={{left:`${fake*100}%`}}/></div><p><ShieldAlert/>This signal supports screening. It is not proof of manipulation.</p></Glass>
      <Glass className="ai-explanation"><div className="module-head"><span>AI/INTERPRETATION</span><Bot/></div>{data.explanation?<><h3>Summary</h3><p>{data.explanation.summary}</p><h3>Evidence interpretation</h3><p>{data.explanation.evidence_interpretation}</p><h3>Limitations</h3><p>{data.explanation.limitations}</p></>:<button onClick={()=>explain.mutate()} disabled={explain.isPending}><Bot/>{explain.isPending?'GROUNDING…':'GENERATE GROUNDED EXPLANATION'}</button>}</Glass>
      <Glass className="human-review"><div className="module-head"><span>HUMAN/DECISION</span><b>INDEPENDENT</b></div>{data.review&&<div className="current-review"><CheckCircle2/><span><small>CURRENT REVIEW</small><b>{label(data.review.decision)}</b></span></div>}<div className="review-actions"><button onClick={()=>review.mutate('CONFIRM_AUTHENTIC')}>CONFIRM AUTHENTIC</button><button onClick={()=>review.mutate('CONFIRM_MANIPULATED')}>CONFIRM MANIPULATED</button><button onClick={()=>review.mutate('MARK_INCONCLUSIVE')}>MARK INCONCLUSIVE</button><button onClick={()=>review.mutate('MARK_FOR_REVIEW')}>REVIEW FURTHER</button></div><label><span><MessageSquarePlus/> REVIEW NOTE</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Record human observations without changing the model output."/><button disabled={!note.trim()||addNote.isPending} onClick={()=>addNote.mutate()}>ADD NOTE</button></label></Glass></aside></div></div>}
